name: GitHub Snake animation

on:
  schedule:
    - cron: '0 * * * *'  # roda a cada hora
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snake Script
        uses: LanneFV/github-readme-snake-action@latest
        with:
          color: '#FFC0CB'        # Rosa bebê
          background: '#800020'   # Vermelho vinho
