on:
  schedule:
    - cron: '0 * * * *'  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snake Script
        uses: LanneFV/github-readme-snake-action@latest
        with:
          color: '#FFC0CB'
          background: '#800020' 
