name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: platane/snk@v3
        with:
          github_user_name: 'LanneFV' # Seu nome de usuário do GitHub
          outputs: dist/snake.svg
